# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'eu.gcr.io/$PROJECT_ID/java14:latest'
  - '.'

images:
- 'eu.gcr.io/$PROJECT_ID/java14:latest'
tags: ['cloud-builders-community']
